### ISSUE TITLE
Are there any weights that can be used for validation?

### ISSUE THREAD

**Issue by Planetdtudy** [Haoyulance/WPSS#1]
Hello, I am trying to use your code. I just downloaded everything and want to try. Can you, please provide the example of testing. Like what should be the parameters:python predict.py --gpu= --weights= --dataset= --modality=
I was trying to do python3 predict.py --gpu=0 --weights=None --dataset=None --modality=t1w, but it provides a lot of errors. 
Thank you very much.

**Comment by Haoyulance** [comment]
Please assign the correct path where the trained model weights are saved and the path where the testing data is saved. Assigning 'None' to --weights and --dataset won't work. 

Best,

**Comment by Planetdtudy** [comment]
Thank you very much. Can i be provided with any trained model weights, so I could validate this method on my dataset?
